language: csharp
mono: none
os: linux
dist: bionic
dotnet: 3.1

before_script:
- export PATH="$PATH:$HOME/.dotnet/tools"

script:
# Echo run data
- REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
- REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
- REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
- echo $TRAVIS_COMMIT
- echo $TRAVIS_BRANCH
- echo $TRAVIS_TAGS
- echo $REPO_COMMIT_AUTHOR
- echo $REPO_COMMIT_AUTHOR_EMAIL
- echo $REPO_COMMIT_MESSAGE
- echo $TRAVIS_JOB_ID
# Tests
- bash scripts/run-tests.sh .
# Coveralls
- dotnet tool install -g coveralls.net --version 2.0.0-beta0002
- csmacnz.Coveralls --reportgenerator -i artifacts/coverage/report/ --repoToken $COVERALLS_REPO_TOKEN
  --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR"
  --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE"
  --jobId $TRAVIS_JOB_ID --serviceName "travis-ci" --useRelativePaths
  
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy-packages.sh
  on:
    tags: true # only deploys if a git TAG exists for the commit
